-- local on_attach = require("plugins.configs.lspconfig").on_attach
-- local capabilities = require("plugins.configs.lspconfig").capabilities
--
-- local lspconfig = require "lspconfig"
--
-- local servers = {
--   "bashls",
--   "cssls",
--   "denols",
--   "dockerls",
--   "dotls",
--   "eslint",
--   "golangci_lint_ls",
--   "gopls",
--   "html",
--   "jsonls",
--   "nil_ls",
--   "pylsp",
--   "pyre",
--   "pyright",
--   "quick_lint_js",
--   "sqlls",
--   "sqls",
--   -- "sumneko_lua", -- 在 plugins/configs/lspconfig.lua 已经配置
--   "tailwindcss",
--   "tsserver",
--   "vls",
--   "volar",
--   "vuels",
--   "yamlls"
-- }
--
-- for _, lsp in ipairs(servers) do
--   lspconfig[lsp].setup {
--     on_attach = on_attach,
--     capabilities = capabilities,
--   }
-- end
--
-- lspconfig["gopls"].setup{}
